### ISSUE TITLE
Discord Server Link?

### ISSUE THREAD

**Issue by AchimTuran** [guip97/ProceduralRecoilAnimationSystem#4]
Hi @guip97,

we really love your plugin and made it work with our Team-FMG forked https://github.com/dyanikoglu/ALS-Community version.

Now we would love to share the experience within the community, which is the reason why we wanted to join the Discord community of this plugin. But somehow the link seems to be missing, see https://github.com/guip97/ProceduralRecoilAnimationSystem/blame/main/README.md#L37. 

Could you please provide us the link the Discord server?

Best Regards
Mohid and Achim.

**Comment by guip97** [comment]
Hello @AchimTuran 
Glad to know that you've got the plugin working with another asset.
Here's a discord link: https://discord.gg/4cPWVEEk
